### PR TITLE
fix: discover skills under .github/skills/ directory

### LINKED ISSUE #52: Waza doesn't understand skills under the .github directory
## Detailed Description

Waza does not discover skills located in `.github/skills/` — a standard location used by GitHub Copilot for project-level skills. Users must manually add `paths.skills: .github/skills` in `.waza.yaml` as a workaround, but this only replaces the default `skills/` path instead of supplementing it. Skills in `.github/skills/` should be found automatically.

## Root Cause

There are two independent code paths that both exclude `.github/skills/`:

### 1. `internal/workspace/workspace.go` — `DetectContext()` and `scanForSkills()`

`DetectContext()` step 3 only checks a single configured `skillsDir` (default `"skills/"`):

```go
skillsDir := filepath.Join(absDir, o.skillsDir)
if isDir(skillsDir) {
    skills := scanForSkills(skillsDir)
    ...
}
```

It never checks `.github/skills/` unless the user explicitly overrides `paths.skills` in `.waza.yaml` — and even then, it replaces the default rather than adding to it.

Step 4 scans immediate children for `SKILL.md`, but `scanForSkills()` explicitly skips hidden directories:

```go
for _, entry := range entries {
    if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
        continue // ← skips .github
    }
    ...
}
```

### 2. `internal/discovery/discovery.go` — `Discover()`

The `Discover()` function (used by `waza run --discover`) also skips hidden directories during its `filepath.Walk`:

```go
if info.IsDir() && strings.HasPrefix(info.Name(), ".") {
    return filepath.SkipDir // ← skips entire .github tree
}
```

## Reproduction Steps

1. Create a skill in `.github/skills/my-skill/SKILL.md`
2. Run any waza command that detects the workspace (e.g., `waza run my-skill`, `waza dev my-skill`, `waza tokens check`)
3. **Expected**: Skill is discovered
4. **Actual**: `no skills detected in workspace` error

## Current Workaround

Add to `.waza.yaml`:

```yaml
paths:
  skills: .github/skills
```

This only works if **all** skills are in `.github/skills/`. If some are in `skills/` and some in `.github/skills/`, there is no workaround since `paths.skills` only supports a single directory.

### Phase 1: `internal/workspace/workspace.go`

Modify `DetectContext()` to also search `.github/skills/` as a built-in secondary skills location:

- After step 3 (checking configured `skillsDir`), also check `.github/skills/` if it exists
- Merge skills from both locations, deduplicating by name (configured `skillsDir` wins on conflict)
- This approach is backward-compatible and requires zero config changes

The `scanForSkills()` function does not need changes since it will be called with `.github/skills` as the parent directory directly (not `.github`).

### Phase 2: `internal/discovery/discovery.go`

Modify `Discover()` to exempt `.github` from the hidden-directory skip:

```go
if info.IsDir() && strings.HasPrefix(info.Name(), ".") && info.Name() != ".github" {
    return filepath.SkipDir
}
```

This ensures `waza run --discover` also finds skills under `.github/skills/`.

### Tests to Add

**`internal/workspace/workspace_test.go`:**
- `TestDetectContext_GitHubSkillsDir` — skills in `.github/skills/` are auto-discovered
- `TestDetectContext_BothSkillsDirs` — skills in both `skills/` and `.github/skills/` are merged
- `TestDetectContext_GitHubSkillsDirWithCustomOverride` — custom `paths.skills` + `.github/skills/` both work
- `TestDetectContext_GitHubSkillsDirDedup` — same skill name in both dirs resolves correctly

**`internal/discovery/discovery_test.go`:**
- `TestDiscoverGitHubSkillsDir` — `Discover()` finds skills under `.github/skills/`
- `TestDiscoverOtherHiddenDirsStillSkipped` — `.hidden/` directories other than `.github` remain skipped

## Files to Modify

| File | Change |
|------|--------|
| `internal/workspace/workspace.go` | Add `.github/skills/` as secondary search path in `DetectContext()` |
| `internal/workspace/workspace_test.go` | Add tests for `.github/skills/` discovery and merging |
| `internal/discovery/discovery.go` | Exempt `.github` from hidden-directory skip in `Discover()` |
| `internal/discovery/discovery_test.go` | Add tests for `.github` exemption |

### PR DESCRIPTION
**Pull request by spboyer**
Fixes #52

## Changes

This PR enables waza to automatically discover skills in  (GitHub Copilot's standard location) without requiring manual configuration.

### Phase 1: Workspace Detection ()

Modified  to check both configured skills directory and :
- After checking the configured  (default ), also checks 
- Merges skills from both locations, deduplicating by name (configured dir wins on conflict)
- Backward-compatible: no config changes needed

### Phase 2: Discovery ()

Modified  to exempt  from hidden directory skipping:
- Changed condition to: `if info.IsDir() && strings.HasPrefix(info.Name(), ".") && info.Name() != ".github"`
- Other hidden directories (, , etc.) still skipped

## Tests

Added comprehensive test coverage:

**Workspace tests:**
- `TestDetectContext_GitHubSkillsDir` - Skills in `.github/skills/` auto-discovered
- `TestDetectContext_BothSkillsDirs` - Skills from both locations merged
- `TestDetectContext_GitHubSkillsDirDedup` - Deduplication works correctly
- `TestDetectContext_GitHubSkillsDirWithCustomOverride` - Custom paths.skills + .github/skills both work

**Discovery tests:**
- `TestDiscoverGitHubSkillsDir` - Discover() finds skills under .github/skills/
- `TestDiscoverOtherHiddenDirsStillSkipped` - Other hidden dirs remain skipped

## Verification

✅ All tests pass: `go test ./internal/workspace/ ./internal/discovery/ -v -count=1`
✅ Build succeeds: `go build ./...`
✅ Clean diff: Only touches workspace.go, workspace_test.go, discovery.go, discovery_test.go

### CODE REVIEW

File: internal/workspace/workspace.go [hunk 1]
```diff
@@ -264,6 +283,26 @@ func isDir(path string) bool {
...
+	}
+
+	aResolved := resolve(a)
+	bResolved := resolve(b)
+	if os.PathSeparator == '\\' {
+		return strings.EqualFold(aResolved, bResolved)
+	}
+	return aResolved == bResolved
+}
+
```
Comment (wbreza) [inline internal/workspace/workspace.go:296]: **[Medium]** samePath() has no direct unit test

This function implements non-trivial logic: `filepath.Abs`, `EvalSymlinks`, and Windows case-insensitive comparison. It's only tested indirectly via `TestDetectContext_GitHubSkillsDirCustomPathNoDuplicateScan`. Consider adding a `TestSamePath` with cases like `("a/b", "a/b")`, `("a/../b", "b")`, and on Windows `("A\\B", "a\\b")`.

File: internal/workspace/workspace.go [hunk 2]
```diff
@@ -118,20 +118,39 @@ func DetectContext(dir string, opts ...DetectOption) (*WorkspaceContext, error)
...
+		existingNames := make(map[string]bool)
+		for _, s := range skills {
+			existingNames[s.Name] = true
+		}
+		for _, s := range githubSkills {
+			if !existingNames[s.Name] {
+				skills = append(skills, s)
+				existingNames[s.Name] = true
+			}
 		}
```
Comment (wbreza) [inline internal/workspace/workspace.go]: **[Medium]** Consider extracting skill deduplication into a helper

The merge-with-dedup logic (build name map, append if not seen) is inline. If a third skill source is ever added, this pattern would be duplicated. Extracting to a `mergeSkills(existing, new []SkillInfo) []SkillInfo` helper would improve reuse and testability.
